name: xnap-example
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pip
- pip:
  - torchvision
  - wandb
  - onnxruntime
  - ipykernel
  - librosa
  - pandas
  - seaborn
  - scikit-learn
